### PR TITLE
Issue 24

### PR DESCRIPTION
**Pull request by tcsorrel**
Here are some unit test to cover this issue and the implementation of the proposed fix.
The fix make the deletion test fail due to redirection issue after delete.

### CODE REVIEW

**Comment by kl4us** [comment]
Works yeah ... thanks a lot

**Comment by jphalip** [comment]
Thank you for the patch! It looks good in general but it isn't fully functional as the custom breadcrumbs don't work properly on the history and delete confirmation pages. It's also a bit of a shame that the user lands on URLs like `/admin/treemenus/menu/item_history/<menu_item_pk>/` instead of the nicer `/admin/treemenus/menu/<menu_pk>/items/<menu_item_pk>/history/`.

I think the patch could be simplified a bit. Here's what I suggest: In `history_menu_item`, if `menu_pk` is `None` (i.e. the user is visiting `/admin/treemenus/menu/item_history/<menu_item_pk>/`), then fetch the correct value for `menu_pk` and then redirect the user right away to `/admin/treemenus/menu/<menu_pk>/items/<menu_item_pk>/history/`. This way you will eventually re-enter the `history_menu_item` view with the correct value for `menu_pk` and the breadcrumbs properly. The tests would also be simplified as you wouldn't need to duplicate all the assertions for Django > 1.4 — You would just need add a test to check the redirection. And the same approach could be followed for the `delete_menu_item` view.

Does it make sense, and if so, could you make those changes? Thanks!

**Comment by tcsorrel** [comment]
This fix seems simpler and more robust.
I'll take it into account shortly. I let you know if I face any trouble with these redirections

**Comment by tcsorrel** [comment]
If you are OK with this development, I still have a few questions : 
- Shall I pack all these commits in one ?
- Do you want to keep the changes on travis configuration for issue branches ?

**Comment by jphalip** [comment]
Thank you, that looks pretty good! Just one small comment: for consistency, could you simply add the new view as a method to `MenuAdmin` instead of having it in a separate file? Also, to answer your questions, it'd be great to squash your commits into one and there's no need to add branch name patterns to the Travis configuration.

Thanks again!

**Comment by tcsorrel** [comment]
All done and tests are passed

**Comment by tcsorrel** [comment]
Is there any improvement needed for this pull request ?

**Comment by jphalip** [comment]
Thank you! I'll cut a new release with this fix soon.

**Pull request merged**
