### PR TITLE
Fix reverse_named_url broken in Django 1.5

### PR DESCRIPTION
**Pull request by artscoop**
Fix error on Django 1.5 because of deprecated template tag syntax since Django 1.3.

### CODE REVIEW

**Comment by jphalip** [comment]
Thank you for the patch! I'd like to continue supporting older versions of Django, so could you please update your patch with a conditional statement like in https://github.com/jphalip/django-treemenus/blob/master/treemenus/admin.py#L166 ? Thanks!

**Comment by artscoop** [comment]
Hi !
Done, the code now checks the django version. 1.3 and more use the new tag format. Other versions use the tag without quotes.

**Comment by jphalip** [comment]
Great, thanks!

**Comment by SpectralAngel** [comment]
This is not completely resolved, if the named url has arguments passed as part of the string in the menu, it will fail.

I made a small correction by simply splitting the url from its arguments

https://github.com/SpectralAngel/django-treemenus/commit/f30114c7aba42d04af050bd7f106248c9c553f30

**Comment by jphalip** [comment]
Could you please open a new ticket for this and also add some tests? Thanks!

**Pull request merged**
