### PR TITLE
Issue 32

### PR DESCRIPTION
**Pull request by dhiana**
Fixes issue #32 

Compatible with django prior to 1.4

### CODE REVIEW

**Comment by jphalip** [comment]
Thanks, this looks great! One quick note though: TEMPLATE_DEBUG is just a boolean, so it doesn't seem necessary to use deepcopy. Can that be removed?

**Comment by dhiana** [comment]
I think I've ran into issues without deepcopy, but I'll check it out
tomorrow!

2014-09-21 17:53 GMT-03:00 Julien Phalip notifications@github.com:

**Comment by dhiana** [comment]
Yes, we can remove the deepcopy. But now I know why I had some issues about
it.:grin: Some typo due to IDE autocomplete.

I've released 3 more commits fixing and simplifying things (to amend for my
autocomple mistake!). :wink:

2014-09-21 18:00 GMT-03:00 Dhiana Deva dhiana.deva@gmail.com:

**Comment by jphalip** [comment]
Sorry for the long delay. I've squashed your commits and pushed it in 4b8882fea180079838c18af58d68dfe9547881ed

Thank you so much!

**Pull request closed without merging**
