### PR TITLE
Added Django 1.6 & Python 3 support

### PR DESCRIPTION
**Pull request by ghost**
- Added Python 3 support, 
- Added Django 1.6 support

### CODE REVIEW

**Comment by jphalip** [comment]
Thanks a lot for your awesome work!

However, I would like to keep support for Python 2.5, at least until the treemenus 1.0 release. Could you please update this PR to re-add Python 2.5 support and then I'll merge it.

Thanks again!

**Comment by ghost** [comment]
I returned Python 2.5 tests back, and now I see 2 types of errors:
- for Django 1.4.9 - https://travis-ci.org/lorddaedra/django-treemenus/jobs/13349882
- for Django 1.3.7 or less - https://travis-ci.org/lorddaedra/django-treemenus/jobs/13349879

I think, it's possible to fix them, but I do not sure how to do that... (and intuition says, it will dirty code)

Guides:
http://docs.python.org/dev/howto/pyporting.html#try-to-support-python-2-6-and-newer-only
http://python3porting.com/noconv.html
https://wiki.python.org/moin/PortingPythonToPy3k

Some of my reasons why it's good idea to drop support for Python 2.5 (and 2.6) and Django < 1.4:
- popular practice (http://docs.python.org/dev/howto/pyporting.html#try-to-support-python-2-6-and-newer-only)
- more clean and simple codebase
- Python 2.5 is outdated, there is no official documentation (on their site) and bugfixes for this release. Python 2.6 is outdated too. "All official maintenance for Python 2.6, including security patches, has ended." (source: http://www.python.org/download/releases/2.6.9/)
- All `stable` linux distributions support at least Python 2.6 (Debian - 2.7.3 (http://distrowatch.com/table.php?distribution=debian), RedHat - 2.6.6 (http://distrowatch.com/table.php?distribution=redhat), Gentoo - 3.2.2 (http://distrowatch.com/table.php?distribution=gentoo))
- Even if it's not possible to update system (evil sysadmin, you know) - there are projects like https://github.com/yyuu/pyenv or https://github.com/saghul/pythonz - so it's possible to use 2.7 python + without admin rights and it will more easily than keeping Python 2.5 support with Python 3.
- Django itself support 2 latest versions -- we will see Django 1.6 release soon and Django 1.5 and 1.6 do not support Python 2.5.

**Comment by jw** [comment]
Dear all,

+1 for lorddaedra

Regards,
jw

**Comment by jphalip** [comment]
Hi,

First of all, thanks a lot for all your efforts working on this PR. This is really appreciated!

The main reason I want to keep Python 2.5 support at this point is because there are people who are still using it. I'm all for eventually dropping that support but only in 1.0, which I'm hoping to cut in the near future.

The first failure is due to Django 1.4.9 introducing an incompatibility. This was fixed in 1.4.10 (https://github.com/django/django/commit/848a7594748c0124a208425dbf0fd2cc861995c3) so if you upgrade that requirement then that error should go away.

For the second failure, why did you add the line `from imp import reload`? Is that necessary for Python 3? If so then you could just import it specifically for Python 3.

Also, why did you modify all the string formats from the `%` syntax to the `"{1}".format(xxx)` syntax? This will cause unnecessary failures in Python < 2.6.

One more question, why did you move the tests to a separate file `test.py`? Why not leave them in the `tests` module?

Generally I think the code in this PR introduces a few too many unneeded changes. I would prefer if it focused purely on adding Python 3 support. This would make it a lot easier to understand the changes and this would also reduce the likelihood of breaking compatibility with older versions of Django and Python.

Now, this PR is starting to get a bit complex with a lot of commits. Would you mind starting a new PR containing only the changes for adding Python 3? If you can do that then I'd be really happy to push all of this forward.

Thanks again very much!

**Comment by ghost** [comment]
Hi!

> First of all, thanks a lot for all your efforts working on this PR. This is really appreciated!

Thank you for this app. :-) 

> The main reason I want to keep Python 2.5 support at this point is because there are people who are still using it. I'm all for eventually dropping that support but only in 1.0, which I'm hoping to cut in the near future.

Python 2.5 is official unsupported by community. And not "yesterday" (like Python 2.6, less than 1 month) - some years. 
Unsupported means no new security releases and bugfixes. Support Python 2.5 is disservice for this people. They don't care about their own safety. Encourage them for using it (keeping support for any outdated software) is bad idea. We will help them much more (I mean server security) if we will never support outdated software... 

> The first failure is due to Django 1.4.9 introducing an incompatibility. This was fixed in 1.4.10 (django/django@848a759) so if you upgrade that requirement then that error should go away.

I fixed travis config. He will check only latest releases in future.

> For the second failure, why did you add the line from imp import reload? Is that necessary for Python 3? If so then you could just import it specifically for Python 3.

Thank you!.. I fixed this...

> Also, why did you modify all the string formats from the % syntax to the "{1}".format(xxx) syntax? This will cause unnecessary failures in Python < 2.6.

New style... In my projects I usually use "{}".format(xxx) syntax (Python 2.7+)...
I changed back to % syntax (for Python 2.5 compatibility) but I like new style more because it's new and recommended...

> One more question, why did you move the tests to a separate file test.py? Why not leave them in the tests module?

Django 1.6+ require it to run tests. (or it will find 0 tests) https://docs.djangoproject.com/en/dev/releases/1.6/#discovery-of-tests-in-any-test-module

> Generally I think the code in this PR introduces a few too many unneeded changes. I would prefer if it focused purely on adding Python 3 support. This would make it a lot easier to understand the changes and this would also reduce the likelihood of breaking compatibility with older versions of Django and Python.
> 
> Now, this PR is starting to get a bit complex with a lot of commits. Would you mind starting a new PR containing only the changes for adding Python 3? If you can do that then I'd be really happy to push all of this forward.

Really I did it for my project (Python 3 + Django 1.6) and I do not have interest in this changes separately... I migrated Python 2.7 & Django 1.5.4 => Python 3.3 & Django 1.6c1 (now => 1.6)

Thanks again very much for creating this app! =) 

GREEN :-)))

http://rack.3.mshcdn.com/media/ZgkyMDEzLzA4LzA1L2VhL2x1Y3loYWxlLmZjZGMwLmdpZgpwCXRodW1iCTg1MHg1OTA-CmUJanBn/49d61cd5/20f/lucy-hale.jpg

**Comment by jphalip** [comment]
Thank you for your updates! I've just made a few more changes here: #28 
Let me know if you have any more feedback. Otherwise I'll just squash everything into one commit (and keep you as the author, of course) and finally merge this.

Thanks!

**Comment by ghost** [comment]
May be it's good idea to clean tests/urls.py (remove `if django.VERSION >= (1, 1):` line) because of we don't run tests for Django==1.0.x

Also I suggest to use flake8 (https://flake8.readthedocs.org/en/2.0/) and fix warnings if exists... 

And I think, no more feedback by now... 

I see some bugs but they are not related with Django 1.6 & Python3...

(Redirect to homepage for urls like http://expo-asia.ru/admin/treemenus/menu/item_history/91/ and http://expo-asia.ru/admin/treemenus/menu/item_delete/91/ )

**Comment by jphalip** [comment]
Ok, merged in master, and released in 0.9.0!

Thanks again for all your hard work!

**Pull request closed without merging**
